name: Test Runner Local

on:
  workflow_dispatch:   # Cho phép chạy thủ công từ GitHub UI
  push:                # Hoặc chạy mỗi khi push code vào repo

jobs:
  test:
    runs-on: self-hosted   # BẮT BUỘC: để job chạy trên local runner
    steps:
      - name: Say Hello
        run: echo "Hello World from Local Runner!"
